/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/XptPPXWPeHC
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import {useEffect, useState} from "react";

export function ContactUsForm() {
  const [name, setName] = useState('')
  const [email, setEmail] = useState('')
  const [message, setMessage] = useState('')
  const [mailto, setMailto] = useState(`pawtrack@gmail.com?subject=Support (Name-Email)&body=Message`)

  useEffect(() => {
    setMailto(`pawtrack@gmail.com?subject=Support (${name}-${email})&body=${message}`)
  }, [name, email, message]);
  
  return (
    <div className="flex min-h-screen flex-col">
      <main className="flex-1 py-12 md:py-16 lg:py-20 bg-white">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 gap-8 md:grid-cols-2">
            <div className="space-y-6">
              <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Get in touch</h1>
              <p className="text-gray-500 dark:text-gray-400">
                Have a question or want to work together? Fill out the form below and we'll get back to you as soon as
                possible.
              </p>
              <form className="space-y-4">
                <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                  <div className="space-y-2">
                    <Label htmlFor="name">Name</Label>
                    <Input id="name" placeholder="John Doe" required type="text"  onChange={(e) => setName(e.target.value)}/>
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="email">Email</Label>
                    <Input id="email" placeholder="m@example.com" required type="email"  onChange={(e) => setEmail(e.target.value)}/>
                  </div>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="message">Message</Label>
                  <Textarea className="min-h-[120px] mb-2" id="message" placeholder="How can we help you?" required onChange={(e) => setMessage(e.target.value)}/>
                </div>
                <a href={`mailto:${mailto}`} className="mt-4">
                  <Button className="w-full py-2" type="button">
                    Send Email
                  </Button>
                </a>
              </form>
            </div>
            <div className="space-y-6">
              <h2 className="text-2xl font-bold tracking-tight">Our headquarters</h2>
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                <div className="space-y-2">
                  <h3 className="text-lg font-medium">San Francisco</h3>
                  <p className="text-gray-500 dark:text-gray-400">123 Main St, San Francisco, CA 94105</p>
                  <p className="text-gray-500 dark:text-gray-400">Phone: (123) 456-7890</p>
                </div>
                <div className="space-y-2">
                  <h3 className="text-lg font-medium">New York</h3>
                  <p className="text-gray-500 dark:text-gray-400">456 Broadway, New York, NY 10013</p>
                  <p className="text-gray-500 dark:text-gray-400">Phone: (987) 654-3210</p>
                </div>
              </div>
              <div className="aspect-video w-full overflow-hidden rounded-lg">
                <img
                  alt="Map"
                  className="h-full w-full object-cover"
                  height="450"
                  src="https://source.unsplash.com/random/?dog"
                  style={{
                    aspectRatio: "800/450",
                    objectFit: "cover",
                  }}
                  width="800"
                />
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
