/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/G506JCBQz7U
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {Link} from "react-router-dom";
import {LuDog} from "react-icons/lu";

export function HomeHeroSection() {
  return (
    <section className="w-full">
      <div className="container px-4 md:px-6">
        <div className="grid items-center gap-10 grid-cols-[1fr_500px]">
          <img
            alt="Happy Pet"
            className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
            height="400"
            src="https://source.unsplash.com/random/?dog"
            width="400"
          />
          <div className="flex flex-col justify-center space-y-4">
            <div className="space-y-2">
              <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none">
                Take care of your Furry Friends
              </h1>
              <p className="max-w-[800px] text-gray-500 md:text-xl dark:text-gray-400 py-2">
                Our app helps you to take care of your pets and keep them healthy and happy by providing diets that are suitable for your pet.
              </p>
            </div>
            <div className="flex flex-col gap-2 min-[400px]:flex-row">
              <Link
                className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                to="/login"
              >
                <LuDog className="w-6 h-6 mr-2"/>
                Login to Pawtrack
              </Link>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
